version: "3.9"

services:
  database:
    image: "postgres:13.2-alpine"
    container_name: simplecrud_test_db
    volumes:
      - ./database:/data/db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=testdb
    ports: 
      - 5432:5432
    networks:
      - backend

  api:
    image: "simplecrud:latest"
    build:
      context: ./api
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - web
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/testdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  web:
    image: web
    build: ./web
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - web

networks:
  web:
    driver: bridge
  backend:
    driver: bridge